version: '3.8'
services:
  server:
    container_name: vls-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      # - postgres
      - redis
    env_file:
      - .env

  # postgres:
  #   image: postgres
  #   container_name: postgres
  #   restart: always
  #   ports:
  #     - ${DATABASE_PORT}:5432
  #   env_file:
  #     - .env
  #   volumes:
  #     - /var/www/vls/postgres:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - /var/www/vls/redis:/data
